SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }

		public int TotalPages
		{
			get
			{
				return (int) Math.Ceiling((decimal) TotalItems/ItemsPerPage);
			}
		}
	}
}

SportsStore/SportsStore.WebUI/ViewModels/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.ViewModels
{
	public class ProductsListViewModel
	{
		public IEnumerable<Product> Products { get; set; }
		public PagingInfo PagingInfo { get; set; }
		public string CurrentCategory { get; set; }
	}
}

SportsStore/SportsStore.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
	public class NavigationController : Controller
	{
		private readonly IProductRepository _repository;

		public NavigationController(IProductRepository repository)
		{
			_repository = repository;
		}

		public PartialViewResult Menu(string category = null)
		{
			ViewBag.SelectedCategory = category;

			var categories = _repository.Products.Select(p => p.Category)
				.Distinct()
				.OrderBy(c => c);

			return PartialView(categories);
		}
	}
}

SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using System.Linq;
using System.Web.Mvc;
using SportsStore.WebUI.Models;
using SportsStore.WebUI.ViewModels;

namespace SportsStore.WebUI.Controllers
{
	public class ProductController : Controller
	{
		private readonly IProductRepository _repository;

		public int PageSize = 4;

		public ProductController(IProductRepository productRepository)
		{
			_repository = productRepository;
		}

		public ViewResult List(string category, int page = 1)
		{
			var viewModel = new ProductsListViewModel
			{
				Products = _repository.Products
					.Where(p => string.IsNullOrEmpty(category) || (p.Category == null || p.Category == category))
					.OrderBy(p => p.ProductID)
					.Skip((page - 1) * PageSize)
					.Take(PageSize),
				PagingInfo = new PagingInfo
				{
					CurrentPage = page,
					ItemsPerPage = PageSize,
					TotalItems = category == null ? 
								_repository.Products.Count() :
								_repository.Products.Count(e => e.Category == category)
				},
				CurrentCategory = category
			};

			return View(viewModel);
		}
	}
}

SportsStore/SportsStore.WebUI/Views/Navigation/Menu.cshtml
@model IEnumerable<string>
		   
@Html.ActionLink("Home", "List", "Product")

@foreach (var link in Model)
{
	@Html.RouteLink(link, new
	{
		controller = "Product",
		Action = "List",
		category = link,
		page = 1
	},
	new
	{
		@class = link == ViewBag.SelectedCategory ? "selected" : null
	})
}

SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@using SportsStore.WebUI.HtmlHelpers
@model SportsStore.WebUI.ViewModels.ProductsListViewModel
@{
	ViewBag.Title = "Products";
}

@foreach (var product in Model.Products)
{
	Html.RenderPartial("ProductSummary", product);
}
<div class="pager">
	@Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
	<h3>@Model.Name</h3>
	@Model.Description
	<h4>@Model.Price.ToString("C")</h4>	
</div>

SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
</head>

<body>
	<div id="header">
		<div class="title">SPORTS STORE</div>
	</div>
	<div id="categories">
		@{ Html.RenderAction("Menu", "Navigation"); }
	</div>
	<div id="content">
		@RenderBody()
	</div>
</body>
</html>